### PR TITLE
[PATCH] Add TS types

### PR DESCRIPTION
**Pull request by kschat**
TS types

### CODE REVIEW

**Review by guyellis — APPROVED** [review]
LGTM

**Comment by ChrisCrewdson** [comment]
@kschat What would it take to ensure that these types are correct and match the code? Is there some transpilation we could trigger just to check? I am worried about the types drifting in the future.

**Comment by kschat** [comment]
That's a good concern. We can write [tests for the types](https://hackernoon.com/testing-types-an-introduction-to-dtslint-b178f9b18ac8), but that's still a bit manual. I think the best way to ensure the implementation matches the types is to write the module in TypeScript.

**Review by ChrisCrewdson — APPROVED** [review]
LGTM

**Pull request merged**
